name: Deploy to EasyPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X GET "${{ secrets.EASYPANEL_DEPLOY_HOOK }}"
